name: Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: "🔑 Checkout"
        uses: actions/checkout@v6

      - name: "🐰 Setup Bun"
        uses: oven-sh/setup-bun@main
        with:
          bun-version: latest

      - name: "Install Dependencies"
        run: bun install --frozen-lockfile
        
      - name: "Setup Biome"
        uses: biomejs/setup-biome@main
        with:
          version: latest

      - name: "Format & Lint, & Type Check"
        run: |
          biome ci .
          bun tsgo --project tsconfig.json --noEmit

      - name: "Build"
        env:
          NODE_ENV: 'production'
        run: bun vite build --mode='production'

      - name: "Test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun vitest --coverage
